# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Companion Material README
#+AUTHOR: Alles et al.

#+STARTUP: overview indent

* Introduction

This is the companion repository for the paper entitled *Measuring
Phenology Uncertainty with Large Scale Image Processing*, by Guilherme
Rezende Alles, João L. D. Comba, Jean-Marc Vincent, Shin Nagai, and
Lucas Mello Schnorr.

The code snippets presented in this repository are written in R, and
can be used to generate the Figures from the paper. While some Figures
are embedded with no extra manipulation, others are annotated with the
help of external tools to enrich the original paper's explanation.

The output from each of the R scripts is a pdf file with the
corresponding image.

** Requirements
This companion material was written in the R programming language, and
all the scripts make heavy use of the [[https://www.tidyverse.org/][tidyverse]]. In order to reproduce
the work contained in this repository, both environments should be
installed. We also use the [[https://cran.r-project.org/web/packages/colorspace/vignettes/colorspace.html#installation][colorspace]] library for color palette
manipulation.

This work was tested in the following R environment:

#+BEGIN_SRC R :results output :exports both
library(tidyverse)
library(colorspace)
sessionInfo()
#+END_SRC

#+RESULTS:
#+begin_example
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] C/UTF-8/C/C/C/C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] colorspace_1.3-2 forcats_0.3.0    stringr_1.3.1    dplyr_0.7.7     
 [5] purrr_0.2.5      readr_1.1.1      tidyr_0.8.1      tibble_1.4.2    
 [9] ggplot2_3.0.0    tidyverse_1.2.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       cellranger_1.1.0 pillar_1.3.0     compiler_3.5.1  
 [5] plyr_1.8.4       bindr_0.1.1      tools_3.5.1      jsonlite_1.5    
 [9] lubridate_1.7.4  gtable_0.2.0     nlme_3.1-137     lattice_0.20-35 
[13] pkgconfig_2.0.2  rlang_0.3.0      cli_1.0.1        rstudioapi_0.8  
[17] haven_1.1.2      bindrcpp_0.2.2   withr_2.1.2      xml2_1.2.0      
[21] httr_1.3.1       hms_0.4.2        grid_3.5.1       tidyselect_0.2.5
[25] glue_1.3.0       R6_2.3.0         readxl_1.1.0     modelr_0.1.2    
[29] magrittr_1.5     backports_1.1.2  scales_1.0.0     rvest_0.3.2     
[33] assertthat_0.2.0 stringi_1.2.4    lazyeval_0.2.1   munsell_0.5.0   
[37] broom_0.5.0      crayon_1.3.4    
#+end_example

** Clone this repository

The [[./data/]] directory on this repository contains the histograms
extracted from phenological images in the form of compressed CSV
files. There are 3 histogram files, and their sizes vary from ~210MB
to ~465MB.

These files are tracked with git LFS. To clone the repository without
histograms data:

#+BEGIN_SRC sh
GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/guilhermealles/phenology-analysis-companion.git
#+END_SRC

In case you want to pull the histograms data afterwards (roughly 1GB):

#+BEGIN_SRC sh
git lfs pull
#+END_SRC

** Datasets Overview Description

There are three datasets explored in the original paper, for which we
provide pre-processed histograms. The datasets are detailed in the
following table.

|-----+--------------------+----------------+---------------------+------------------+--------------|
| ID  | Dataset            | Location       | Vegetation Type     | Image Resolution | Images Count |
|-----+--------------------+----------------+---------------------+------------------+--------------|
| TKY | Takayama Flux Site | Japan          | Deciduous Broadleaf |        2272x1704 |        20561 |
| AHS | Alice Holt         | United Kingdom | Deciduous Brodleaf  |        2272x1704 |        55139 |
| MTK | Mt. Tsukuba        | Japan          | Mixed Forest        |        2272x1704 |        71875 |
|-----+--------------------+----------------+---------------------+------------------+--------------|
** Scripts for re-creating the Figures
The scripts needed to reproduce the Figures are located in the
[[./scripts/]] directory from this repository.
